apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-07-08T06:02:44Z"
  labels:
    app: n1
  name: n1
  namespace: default
  resourceVersion: "482621"
  uid: 5ea1c9a6-927f-460b-a3da-c17fbcba9535
spec:
  clusterIP: 10.233.63.73
  clusterIPs:
  - 10.233.63.73
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31726
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: n1
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
